"""spots and pass spot_id

Revision ID: b5d73c339fd1
Revises: d1243f6f627a
Create Date: 2026-07-28 11:06:17.393665
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = 'b5d73c339fd1'
down_revision: str | None = 'd1243f6f627a'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('spots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('spot_type', sa.String(length=32), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('last_vacated_at', sa.DateTime(), nullable=True),
    sa.Column('overstay_reported', sa.Boolean(), nullable=False),
    sa.Column('overstay_reported_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('spots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_spots_number'), ['number'], unique=True)

    with op.batch_alter_table('parking_passes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('spot_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_parking_passes_spot_id'), ['spot_id'], unique=False)
        batch_op.create_foreign_key('fk_parking_passes_spot_id', 'spots', ['spot_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('parking_passes', schema=None) as batch_op:
        batch_op.drop_constraint('fk_parking_passes_spot_id', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_parking_passes_spot_id'))
        batch_op.drop_column('spot_id')

    with op.batch_alter_table('spots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_spots_number'))

    op.drop_table('spots')
    # ### end Alembic commands ###
